site_name: My Docs for API course

theme:
  name: dracula
  favicon: logo.png

nav:
 - About website: index.md
 - API Docs structure: structure.md
 - Tools, which we studied: tools.md
 - API reference: dist/index.html
 - My job after course: for_me.md

